-- Aplicada: PENDIENTE (Julio, por MCP).
--
-- ENCARGO fix/kds-latido-raiz · Tarea B — vigía de salud de BBDD.
-- El 11/08 nos enteramos de la caída porque la app no cargaba: no había nada que
-- avisara ANTES. Este vigía cierra ese hueco: RPC de chequeo + cron cada minuto +
-- rastro con retención corta + aviso por el canal de notificaciones YA EXISTENTE
-- (edge `system-alert`, ya versionada en supabase/functions/system-alert — no se
-- crea edge nueva, no hace falta: el patrón "cron llama a system-alert vía
-- net.http_post con x-cron-secret de Vault" ya existe en producción, ver el cron
-- `hubrise-order-stuck-watchdog`, que este vigía calca).
--
-- Umbral del encargo ("más de 3 procesos esperando lock durante más de 2
-- min") — interpretación corregida (Julio, 2ª vuelta): lo que importa es que
-- el CONTEO agregado de procesos esperando lock lleve sostenido por encima de
-- 3 durante 2 minutos, no que cada proceso individual lleve él mismo 2 min
-- bloqueado. db_health_snapshot() ahora es un chequeo instantáneo (conteo
-- crudo de wait_event_type='Lock', sin filtro de tiempo); la persistencia se
-- mide en db_health_watchdog() mirando los snapshots ya guardados en
-- db_health_snapshot_log de los últimos 2 minutos: dispara solo si TODOS los
-- snapshots de esa ventana rompen el umbral Y hay al menos 2 (una sola
-- lectura, aunque rompa, no basta para llamarlo "sostenido" — evita un falso
-- positivo en el primer minuto de vida del cron o justo tras un reinicio).
-- Con el cron a */1 min, 2 snapshots consecutivos cubren la ventana de 2 min
-- pedida por el encargo.
--
-- SIN CATCH MUDO: si el propio chequeo falla (p.ej. pg_stat_activity no
-- accesible), el vigía intenta avisar de ESE fallo por el mismo canal y luego
-- relanza la excepción (queda también en cron.job_run_details).
--
-- Antiruido: no repite el aviso de bloqueo si ya avisó en los últimos 15 min
-- mientras la condición persiste (evita spam de 1 email/minuto en un incidente
-- largo, sin dejar de avisar del inicio y de una posible recaída).
--
-- Validado por MCP antes de escribir este fichero: compiló y corrió con
-- nombres temporales _tmp_check_*, y la lógica de persistencia se probó
-- aparte con 3 casos (ambos snapshots rompen -> dispara; uno solo rompe de
-- dos -> no dispara; una sola lectura aunque rompa -> no dispara) — regla
-- "validar SQL por MCP antes de entregar".

-- ── 1) Tabla de rastro (retención corta, deny-all — patrón F0.3) ──────────────

create table if not exists public.db_health_snapshot_log (
  id                 bigint generated by default as identity primary key,
  checked_at         timestamptz not null default now(),
  total_connections  int not null,
  waiting_locks      int not null,
  oldest_tx_seconds  numeric not null,
  alerted            boolean not null default false
);

comment on table public.db_health_snapshot_log is
  'RLS deny-all intencional (vigía interno de salud de BBDD). Acceso solo vía '
  'SECURITY DEFINER (fix/kds-latido-raiz, 11/08). Retención: 48h, se autolimpia '
  'en cada ejecución de db_health_watchdog(). waiting_locks = conteo crudo de '
  'pg_stat_activity con wait_event_type=Lock en el momento del snapshot; la '
  'persistencia (>3 durante >2min) se evalúa comparando snapshots consecutivos, '
  'no dentro de esta fila.';

alter table public.db_health_snapshot_log enable row level security;

create index if not exists idx_db_health_snapshot_log_checked_at
  on public.db_health_snapshot_log (checked_at desc);

-- ── 2) RPC de chequeo (puro, instantáneo, sin efectos secundarios) ────────────

CREATE OR REPLACE FUNCTION public.db_health_snapshot()
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
declare
  v_total_conn   int;
  v_waiting_lock int;
  v_oldest_tx_s  numeric;
begin
  select count(*) into v_total_conn from pg_stat_activity;

  select count(*) into v_waiting_lock
  from pg_stat_activity
  where wait_event_type = 'Lock';

  select extract(epoch from max(now() - xact_start)) into v_oldest_tx_s
  from pg_stat_activity
  where xact_start is not null;

  return jsonb_build_object(
    'total_connections', v_total_conn,
    'waiting_locks',     v_waiting_lock,
    'oldest_tx_seconds', coalesce(round(v_oldest_tx_s), 0)
  );
end;
$function$;

comment on function public.db_health_snapshot() is
  'Chequeo puro e instantáneo de salud de BBDD (conexiones, procesos '
  'esperando lock AHORA, tx más vieja). Sin efectos secundarios y sin juicio '
  'de persistencia — eso lo hace db_health_watchdog() comparando snapshots.';

-- ── 3) Vigía: registra + evalúa persistencia + avisa ──────────────────────────

CREATE OR REPLACE FUNCTION public.db_health_watchdog()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
declare
  v_snap        jsonb;
  v_waiting     int;
  v_row_id      bigint;
  v_n_snapshots int;
  v_n_breaching int;
  v_last_alert  timestamptz;
  v_secret      text;
begin
  begin
    v_snap    := public.db_health_snapshot();
    v_waiting := (v_snap->>'waiting_locks')::int;

    insert into public.db_health_snapshot_log
      (total_connections, waiting_locks, oldest_tx_seconds)
    values
      ((v_snap->>'total_connections')::int, v_waiting, (v_snap->>'oldest_tx_seconds')::numeric)
    returning id into v_row_id;

    delete from public.db_health_snapshot_log where checked_at < now() - interval '48 hours';

    -- Persistencia: ¿todos los snapshots de los últimos 2 min rompen el
    -- umbral, y hay al menos 2 para poder llamarlo "sostenido"?
    select count(*), count(*) filter (where waiting_locks > 3)
      into v_n_snapshots, v_n_breaching
      from public.db_health_snapshot_log
      where checked_at >= now() - interval '2 minutes';

    if v_n_snapshots >= 2 and v_n_breaching = v_n_snapshots then
      select max(checked_at) into v_last_alert
      from public.db_health_snapshot_log where alerted;

      if v_last_alert is null or v_last_alert < now() - interval '15 minutes' then
        select decrypted_secret into v_secret from vault.decrypted_secrets where name = 'cron_secret';
        if v_secret is not null then
          perform net.http_post(
            url     := 'https://xzmpnchlguibclvxyynt.supabase.co/functions/v1/system-alert',
            headers := jsonb_build_object('Content-Type', 'application/json', 'x-cron-secret', v_secret),
            body    := jsonb_build_object(
              'subject', 'BBDD con bloqueos — ' || v_waiting || ' proceso(s) esperando lock, sostenido >2min',
              'message', 'db_health_watchdog detectó más de 3 procesos esperando lock en ' || v_n_snapshots
                         || ' snapshots consecutivos de los últimos 2 minutos (ahora mismo: ' || v_waiting || ').' || chr(10)
                         || 'Conexiones totales: ' || (v_snap->>'total_connections')
                         || '. Transacción más antigua: ' || (v_snap->>'oldest_tx_seconds') || 's.' || chr(10)
                         || 'Así empezó el incidente del 11/08 (caída ~45 min con los 3 locales cerrados). Revisar pg_stat_activity ya.',
              'kind', 'db-health'
            ),
            timeout_milliseconds := 10000
          );
          update public.db_health_snapshot_log set alerted = true where id = v_row_id;
        else
          raise warning 'db_health_watchdog: secret cron_secret ausente en Vault, no se pudo avisar';
        end if;
      end if;
    end if;
  exception when others then
    -- Sin catch mudo: si el propio chequeo falla, eso también es un aviso.
    begin
      select decrypted_secret into v_secret from vault.decrypted_secrets where name = 'cron_secret';
      if v_secret is not null then
        perform net.http_post(
          url     := 'https://xzmpnchlguibclvxyynt.supabase.co/functions/v1/system-alert',
          headers := jsonb_build_object('Content-Type', 'application/json', 'x-cron-secret', v_secret),
          body    := jsonb_build_object(
            'subject', 'db_health_watchdog FALLÓ',
            'message', 'El vigía de salud de BBDD lanzó una excepción y no pudo completar su chequeo: ' || sqlerrm,
            'kind', 'db-health-watchdog-error'
          ),
          timeout_milliseconds := 10000
        );
      end if;
    exception when others then
      null; -- último recurso; queda igualmente en cron.job_run_details
    end;
    raise;
  end;
end;
$function$;

comment on function public.db_health_watchdog() is
  'Registra un snapshot de salud cada minuto (cron db-health-watchdog) y avisa '
  'por system-alert si >3 procesos esperan lock de forma sostenida (todos los '
  'snapshots de los últimos 2min, mínimo 2 lecturas). Antiruido: no repite '
  'aviso en <15min mientras persiste. Nunca falla en silencio.';

-- No exponer a clientes: solo el cron (postgres) las llama.
revoke all on function public.db_health_snapshot() from public, anon, authenticated;
revoke all on function public.db_health_watchdog() from public, anon, authenticated;

-- ── 4) Cron cada minuto ────────────────────────────────────────────────────────

select cron.schedule(
  'db-health-watchdog',
  '* * * * *',
  $cron$select public.db_health_watchdog()$cron$
);
