-- ENCARGO fix/kds-latido-raiz · Tarea B — vigia de salud de BBDD.
-- El 11/08 nos enteramos de la caida porque la app no cargaba: no habia nada que
-- avisara ANTES. Vigia = RPC de chequeo + cron cada minuto + rastro con retencion
-- corta + aviso por la edge `system-alert` YA EXISTENTE (patron del cron
-- `hubrise-order-stuck-watchdog`).
--
-- 6 avisos, cada uno con antiruido propio en db_health_alert_log:
--   1) bloqueos sostenidos >2min (persistencia entre snapshots consecutivos)
--   2) conexiones >80% de max_connections
--   3) regresion del guard anti-escritura (writer_count != 3)
--   4) print_job en pending >2h
--   5) print_job no terminal en impresora is_active=false
--   6) pedidos aceptados sin ninguna impresora activa (print_route_failure_log)
--
-- Los 3 escritores LEGITIMOS de kds_device (no tocar sin actualizar el umbral):
--   kds_heartbeat · report_device_app_version · set_device_mode_by_token
--
-- Documentacion extensa (RECON de la causa raiz de Carabanchel, justificacion
-- del umbral, limites conocidos) en el fichero del repo
-- supabase/migrations/20260816T0902_db_health_watchdog.sql

-- 1) Tablas de rastro y de avisos (deny-all)
create table if not exists public.db_health_snapshot_log (
  id                 bigint generated by default as identity primary key,
  checked_at         timestamptz not null default now(),
  total_connections  int not null,
  waiting_locks      int not null,
  oldest_tx_seconds  numeric not null,
  writer_count       int not null
);
comment on table public.db_health_snapshot_log is
  'RLS deny-all intencional (vigia interno de salud de BBDD). Acceso solo via '
  'SECURITY DEFINER (fix/kds-latido-raiz, 11/08). Retencion: 48h. writer_count = '
  'funciones public con `update ... kds_device` — guard anti-regresion, esperado 3.';
alter table public.db_health_snapshot_log enable row level security;
create index if not exists idx_db_health_snapshot_log_checked_at
  on public.db_health_snapshot_log (checked_at desc);

create table if not exists public.db_health_alert_log (
  id      bigint generated by default as identity primary key,
  kind    text not null,
  sent_at timestamptz not null default now(),
  detail  text
);
comment on table public.db_health_alert_log is
  'RLS deny-all intencional. Auditoria + antiruido de los avisos del vigia. '
  'Retencion: 30 dias.';
alter table public.db_health_alert_log enable row level security;
create index if not exists idx_db_health_alert_log_kind_sent_at
  on public.db_health_alert_log (kind, sent_at desc);

create table if not exists public.print_route_failure_log (
  id           bigint generated by default as identity primary key,
  account_id   uuid not null,
  location_id  uuid not null,
  sale_id      uuid,
  doc_type     text,
  detail       text not null,
  created_at   timestamptz not null default now()
);
comment on table public.print_route_failure_log is
  'RLS deny-all intencional. Rastro de "pedido aceptado sin impresora activa" '
  '(fix/limpieza-kds-viejo-y-prevencion, 11/08). La crea tambien la 0904 con '
  'if not exists para que el orden entre 0902 y 0904 no importe.';
alter table public.print_route_failure_log enable row level security;
create index if not exists idx_print_route_failure_log_created_at
  on public.print_route_failure_log (location_id, created_at desc);

-- 2) RPC de chequeo (puro, instantaneo)
CREATE OR REPLACE FUNCTION public.db_health_snapshot()
RETURNS jsonb
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
declare
  v_total_conn   int;
  v_waiting_lock int;
  v_oldest_tx_s  numeric;
  v_writer_count int;
  v_max_conn     int;
begin
  select count(*) into v_total_conn from pg_stat_activity;
  select count(*) into v_waiting_lock
  from pg_stat_activity
  where wait_event_type = 'Lock';
  select extract(epoch from max(now() - xact_start)) into v_oldest_tx_s
  from pg_stat_activity
  where xact_start is not null;
  select count(*) into v_writer_count
  from pg_proc p
  join pg_namespace n on n.oid = p.pronamespace
  where n.nspname = 'public' and p.prosrc ~* 'update\s+(public\.)?kds_device';
  select setting::int into v_max_conn from pg_settings where name = 'max_connections';
  return jsonb_build_object(
    'total_connections', v_total_conn,
    'waiting_locks',     v_waiting_lock,
    'oldest_tx_seconds', coalesce(round(v_oldest_tx_s), 0),
    'writer_count',      v_writer_count,
    'max_connections',   v_max_conn
  );
end;
$function$;
comment on function public.db_health_snapshot() is
  'Chequeo puro e instantaneo de salud de BBDD. Sin efectos secundarios y sin '
  'juicio de persistencia — eso lo hace db_health_watchdog() comparando snapshots.';

-- 3) Vigia
CREATE OR REPLACE FUNCTION public.db_health_watchdog()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
declare
  v_snap            jsonb;
  v_waiting         int;
  v_writers         int;
  v_total_conn      int;
  v_max_conn        int;
  v_n_snapshots     int;
  v_n_breaching     int;
  v_secret          text;
  v_stuck_print     int;
  v_inactive_print  int;
  v_route_failures  int;
begin
  begin
    v_snap       := public.db_health_snapshot();
    v_waiting    := (v_snap->>'waiting_locks')::int;
    v_writers    := (v_snap->>'writer_count')::int;
    v_total_conn := (v_snap->>'total_connections')::int;
    v_max_conn   := (v_snap->>'max_connections')::int;

    insert into public.db_health_snapshot_log
      (total_connections, waiting_locks, oldest_tx_seconds, writer_count)
    values
      (v_total_conn, v_waiting, (v_snap->>'oldest_tx_seconds')::numeric, v_writers);

    delete from public.db_health_snapshot_log where checked_at < now() - interval '48 hours';
    delete from public.db_health_alert_log where sent_at < now() - interval '30 days';

    -- Aviso 1 — bloqueos sostenidos
    select count(*), count(*) filter (where waiting_locks > 3)
      into v_n_snapshots, v_n_breaching
      from public.db_health_snapshot_log
      where checked_at >= now() - interval '2 minutes';
    if v_n_snapshots >= 2 and v_n_breaching = v_n_snapshots
       and not exists (
         select 1 from public.db_health_alert_log
         where kind = 'db-health-lock' and sent_at >= now() - interval '15 minutes'
       ) then
      select decrypted_secret into v_secret from vault.decrypted_secrets where name = 'cron_secret';
      if v_secret is not null then
        perform net.http_post(
          url     := 'https://xzmpnchlguibclvxyynt.supabase.co/functions/v1/system-alert',
          headers := jsonb_build_object('Content-Type', 'application/json', 'x-cron-secret', v_secret),
          body    := jsonb_build_object(
            'subject', 'BBDD con bloqueos — ' || v_waiting || ' proceso(s) esperando lock, sostenido >2min',
            'message', 'db_health_watchdog detecto mas de 3 procesos esperando lock en ' || v_n_snapshots
                       || ' snapshots consecutivos de los ultimos 2 minutos (ahora mismo: ' || v_waiting || ').' || chr(10)
                       || 'Conexiones totales: ' || v_total_conn
                       || '. Transaccion mas antigua: ' || (v_snap->>'oldest_tx_seconds') || 's.' || chr(10)
                       || 'Asi empezo el incidente del 11/08 (caida ~45 min con los 3 locales cerrados). Revisar pg_stat_activity ya.',
            'kind', 'db-health'
          ),
          timeout_milliseconds := 10000
        );
        insert into public.db_health_alert_log (kind, detail) values ('db-health-lock', v_waiting || ' esperando lock');
      end if;
    end if;

    -- Aviso 2 — conexiones cerca del maximo
    if v_max_conn > 0 and v_total_conn > 0.8 * v_max_conn
       and not exists (
         select 1 from public.db_health_alert_log
         where kind = 'db-health-connections' and sent_at >= now() - interval '15 minutes'
       ) then
      select decrypted_secret into v_secret from vault.decrypted_secrets where name = 'cron_secret';
      if v_secret is not null then
        perform net.http_post(
          url     := 'https://xzmpnchlguibclvxyynt.supabase.co/functions/v1/system-alert',
          headers := jsonb_build_object('Content-Type', 'application/json', 'x-cron-secret', v_secret),
          body    := jsonb_build_object(
            'subject', 'BBDD cerca del limite de conexiones — ' || v_total_conn || '/' || v_max_conn,
            'message', 'db_health_watchdog detecto ' || v_total_conn || ' conexiones activas de un maximo de '
                       || v_max_conn || ' (>80%).' || chr(10)
                       || 'Revisar pg_stat_activity: puede ser el mismo patron del 11/08.',
            'kind', 'db-health'
          ),
          timeout_milliseconds := 10000
        );
        insert into public.db_health_alert_log (kind, detail) values ('db-health-connections', v_total_conn || '/' || v_max_conn);
      end if;
    end if;

    -- Aviso 3 — guard anti-regresion. Solo dispara si ALGUNA VEZ hubo un
    -- snapshot con writer_count=3 ("estuvo bien y ahora no"), para no dar
    -- falso positivo antes de aplicar la 0901.
    if v_writers <> 3
       and exists (select 1 from public.db_health_snapshot_log where writer_count = 3)
       and not exists (
         select 1 from public.db_health_alert_log
         where kind = 'db-health-writer-regression' and sent_at >= now() - interval '24 hours'
       ) then
      select decrypted_secret into v_secret from vault.decrypted_secrets where name = 'cron_secret';
      if v_secret is not null then
        perform net.http_post(
          url     := 'https://xzmpnchlguibclvxyynt.supabase.co/functions/v1/system-alert',
          headers := jsonb_build_object('Content-Type', 'application/json', 'x-cron-secret', v_secret),
          body    := jsonb_build_object(
            'subject', 'REGRESION: ' || v_writers || ' funciones escriben kds_device (se esperaban 3)',
            'message', 'Alguien ha vuelto a meter una escritura de last_seen_at en una funcion de LECTURA de kds_device '
                       || '(el incidente completo del 11/08, de nuevo).' || chr(10)
                       || 'Esperado: kds_heartbeat, report_device_app_version, set_device_mode_by_token — y nada mas.',
            'kind', 'db-health'
          ),
          timeout_milliseconds := 10000
        );
        insert into public.db_health_alert_log (kind, detail) values ('db-health-writer-regression', v_writers || ' escritores');
      end if;
    end if;

    -- Aviso 4 — print_job en pending >2h
    select count(*) into v_stuck_print
    from print_job
    where status = 'pending' and created_at < now() - interval '2 hours';
    if v_stuck_print > 0
       and not exists (
         select 1 from public.db_health_alert_log
         where kind = 'db-health-print-stuck' and sent_at >= now() - interval '60 minutes'
       ) then
      select decrypted_secret into v_secret from vault.decrypted_secrets where name = 'cron_secret';
      if v_secret is not null then
        perform net.http_post(
          url     := 'https://xzmpnchlguibclvxyynt.supabase.co/functions/v1/system-alert',
          headers := jsonb_build_object('Content-Type', 'application/json', 'x-cron-secret', v_secret),
          body    := jsonb_build_object(
            'subject', v_stuck_print || ' trabajo(s) de impresion atascados >2h',
            'message', 'db_health_watchdog detecto ' || v_stuck_print || ' print_job en pending desde hace mas de 2 horas.' || chr(10)
                       || 'Asi se acumularon los 76 de Carabanchel (08-09/08) durante 3 dias sin que nadie se enterara.',
            'kind', 'db-health'
          ),
          timeout_milliseconds := 10000
        );
        insert into public.db_health_alert_log (kind, detail) values ('db-health-print-stuck', v_stuck_print || ' trabajos');
      end if;
    end if;

    -- Aviso 5 — print_job no terminal en impresora inactiva (inmediato)
    select count(*) into v_inactive_print
    from print_job pj
    join printer p on p.id = pj.printer_id
    where pj.status in ('pending', 'sent') and p.is_active = false;
    if v_inactive_print > 0
       and not exists (
         select 1 from public.db_health_alert_log
         where kind = 'db-health-print-inactive-printer' and sent_at >= now() - interval '60 minutes'
       ) then
      select decrypted_secret into v_secret from vault.decrypted_secrets where name = 'cron_secret';
      if v_secret is not null then
        perform net.http_post(
          url     := 'https://xzmpnchlguibclvxyynt.supabase.co/functions/v1/system-alert',
          headers := jsonb_build_object('Content-Type', 'application/json', 'x-cron-secret', v_secret),
          body    := jsonb_build_object(
            'subject', v_inactive_print || ' trabajo(s) de impresion encolados a impresora INACTIVA',
            'message', 'db_health_watchdog detecto ' || v_inactive_print || ' print_job (pending/sent) cuya impresora tiene is_active=false.' || chr(10)
                       || 'Nunca se van a imprimir: claim_print_jobs solo reclama de impresoras activas. Cancelalos o reasigna la impresora.',
            'kind', 'db-health'
          ),
          timeout_milliseconds := 10000
        );
        insert into public.db_health_alert_log (kind, detail) values ('db-health-print-inactive-printer', v_inactive_print || ' trabajos');
      end if;
    end if;

    -- Aviso 6 — pedidos aceptados sin ninguna impresora activa
    select count(*) into v_route_failures
    from public.print_route_failure_log
    where created_at >= now() - interval '10 minutes';
    if v_route_failures > 0
       and not exists (
         select 1 from public.db_health_alert_log
         where kind = 'db-health-print-no-active-printer' and sent_at >= now() - interval '60 minutes'
       ) then
      select decrypted_secret into v_secret from vault.decrypted_secrets where name = 'cron_secret';
      if v_secret is not null then
        perform net.http_post(
          url     := 'https://xzmpnchlguibclvxyynt.supabase.co/functions/v1/system-alert',
          headers := jsonb_build_object('Content-Type', 'application/json', 'x-cron-secret', v_secret),
          body    := jsonb_build_object(
            'subject', 'Pedido(s) aceptado(s) sin impresora activa en el local',
            'message', 'db_health_watchdog detecto ' || v_route_failures || ' aviso(s) en print_route_failure_log de los ultimos 10 minutos.' || chr(10)
                       || 'Un local se quedo sin ninguna impresora activa configurada — los pedidos se aceptan pero no imprime nada.',
            'kind', 'db-health'
          ),
          timeout_milliseconds := 10000
        );
        insert into public.db_health_alert_log (kind, detail) values ('db-health-print-no-active-printer', v_route_failures || ' avisos');
      end if;
    end if;

  exception when others then
    -- Sin catch mudo
    begin
      if not exists (
        select 1 from public.db_health_alert_log
        where kind = 'db-health-watchdog-error' and sent_at >= now() - interval '30 minutes'
      ) then
        select decrypted_secret into v_secret from vault.decrypted_secrets where name = 'cron_secret';
        if v_secret is not null then
          perform net.http_post(
            url     := 'https://xzmpnchlguibclvxyynt.supabase.co/functions/v1/system-alert',
            headers := jsonb_build_object('Content-Type', 'application/json', 'x-cron-secret', v_secret),
            body    := jsonb_build_object(
              'subject', 'db_health_watchdog FALLO',
              'message', 'El vigia de salud de BBDD lanzo una excepcion y no pudo completar su chequeo: ' || sqlerrm,
              'kind', 'db-health-watchdog-error'
            ),
            timeout_milliseconds := 10000
          );
          insert into public.db_health_alert_log (kind, detail) values ('db-health-watchdog-error', sqlerrm);
        end if;
      end if;
    exception when others then
      null;
    end;
    raise;
  end;
end;
$function$;
comment on function public.db_health_watchdog() is
  'Registra un snapshot cada minuto (cron db-health-watchdog) y avisa por '
  'system-alert ante 6 condiciones independientes, cada una con su antiruido en '
  'db_health_alert_log. Nunca falla en silencio.';

-- 4) Reporte DIARIO de dispositivos fantasma (solo aviso, SIN baja automatica)
CREATE OR REPLACE FUNCTION public.db_health_stale_devices_report()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
declare
  v_secret text;
  v_list   text;
  v_count  int;
begin
  -- LEFT JOIN a proposito: un dispositivo con location_id NULL es justo el que
  -- mas interesa reportar.
  select string_agg(
           format('%s (%s) — ultimo latido: %s',
             d.label, coalesce(l.name, 'sin local'), coalesce(d.last_seen_at::text, 'nunca')),
           chr(10) order by d.last_seen_at nulls first
         ), count(*)
    into v_list, v_count
  from kds_device d
  left join locations l on l.id = d.location_id
  where d.is_active
    and (d.last_seen_at is null or d.last_seen_at < now() - interval '30 days');

  if v_count is null or v_count = 0 then
    return;
  end if;

  select decrypted_secret into v_secret from vault.decrypted_secrets where name = 'cron_secret';
  if v_secret is null then
    raise warning 'db_health_stale_devices_report: secret cron_secret ausente en Vault, no se pudo avisar';
    return;
  end if;

  perform net.http_post(
    url     := 'https://xzmpnchlguibclvxyynt.supabase.co/functions/v1/system-alert',
    headers := jsonb_build_object('Content-Type', 'application/json', 'x-cron-secret', v_secret),
    body    := jsonb_build_object(
      'subject', v_count || ' dispositivo(s) KDS activo(s) sin latido hace mas de 30 dias',
      'message', 'Solo REPORTE — ninguna baja automatica. Revisar si siguen en uso o dar de baja a mano (is_active=false):'
                 || chr(10) || chr(10) || v_list,
      'kind', 'db-health-stale-devices'
    ),
    timeout_milliseconds := 10000
  );
exception when others then
  begin
    select decrypted_secret into v_secret from vault.decrypted_secrets where name = 'cron_secret';
    if v_secret is not null then
      perform net.http_post(
        url     := 'https://xzmpnchlguibclvxyynt.supabase.co/functions/v1/system-alert',
        headers := jsonb_build_object('Content-Type', 'application/json', 'x-cron-secret', v_secret),
        body    := jsonb_build_object(
          'subject', 'db_health_stale_devices_report FALLO',
          'message', 'El reporte diario de dispositivos fantasma lanzo una excepcion: ' || sqlerrm,
          'kind', 'db-health-stale-devices-error'
        ),
        timeout_milliseconds := 10000
      );
    end if;
  exception when others then
    null;
  end;
  raise;
end;
$function$;
comment on function public.db_health_stale_devices_report() is
  'Reporte DIARIO (cron db-health-stale-devices-daily, 06:00 UTC ~ 08:00 Madrid '
  'en verano) de kds_device con is_active=true y last_seen_at NULL o >30 dias. '
  'Solo aviso — CERO efecto operativo automatico.';

revoke all on function public.db_health_snapshot() from public, anon, authenticated;
revoke all on function public.db_health_watchdog() from public, anon, authenticated;
revoke all on function public.db_health_stale_devices_report() from public, anon, authenticated;

-- 5) Crons
select cron.schedule(
  'db-health-watchdog',
  '* * * * *',
  $cron$select public.db_health_watchdog()$cron$
);

-- 06:00 UTC: cron.timezone del proyecto es GMT fijo sin DST. 06:00 UTC = 08:00
-- Madrid en verano, 07:00 en invierno. pg_cron no soporta DST. Deuda menor.
select cron.schedule(
  'db-health-stale-devices-daily',
  '0 6 * * *',
  $cron$select public.db_health_stale_devices_report()$cron$
);