create table if not exists public.last_catalog_alert_log (
  id      bigint generated by default as identity primary key,
  kind    text not null,
  sent_at timestamptz not null default now(),
  detail  text
);

comment on table public.last_catalog_alert_log is
  'RLS deny-all intencional (vigia interno). Antiruido/auditoria de los avisos de last_catalog_watchdog() - un aviso de un kind no se repite mientras exista una fila reciente de ese kind (ventana de 3h, 30min para el fallo del propio vigia). Retencion: 30 dias.';

alter table public.last_catalog_alert_log enable row level security;

create index if not exists idx_last_catalog_alert_log_kind_sent_at
  on public.last_catalog_alert_log (kind, sent_at desc);

CREATE OR REPLACE FUNCTION public.last_catalog_watchdog()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
declare
  v_secret text;
  v_list   text;
  v_count  int;
begin
  delete from public.last_catalog_alert_log where sent_at < now() - interval '30 days';

  select string_agg(
           format('cuenta %s / org %s - ultimo sync: %s', x.account_id, x.external_org_id,
                  coalesce(x.max_synced::text, 'nunca')),
           chr(10) order by x.max_synced nulls first
         ), count(*)
    into v_list, v_count
  from (
    select ei.account_id, ei.external_org_id,
           (select max(ecp.last_synced_at) from public.external_catalog_product ecp
             where ecp.account_id = ei.account_id and ecp.source = 'lastapp'
               and ecp.external_org_id = ei.external_org_id) as max_synced
    from public.external_integration ei
    where ei.source = 'lastapp' and ei.is_active = true
  ) x
  where x.max_synced is null or x.max_synced < now() - interval '3 hours';

  if v_count > 0
     and not exists (
       select 1 from public.last_catalog_alert_log
       where kind = 'last-catalog-stale' and sent_at >= now() - interval '3 hours'
     ) then
    select decrypted_secret into v_secret from vault.decrypted_secrets where name = 'cron_secret';
    if v_secret is not null then
      perform net.http_post(
        url     := 'https://xzmpnchlguibclvxyynt.supabase.co/functions/v1/system-alert',
        headers := jsonb_build_object('Content-Type', 'application/json', 'x-cron-secret', v_secret),
        body    := jsonb_build_object(
          'subject', 'Espejo de Last rancio - ' || v_count || ' cuenta(s) sin sincronizar hace >3h',
          'message', 'last_catalog_watchdog detecto que el espejo de disponibilidad de Last (external_catalog_product) lleva mas de 3h sin refrescarse en:' || chr(10) || chr(10)
                     || v_list || chr(10) || chr(10)
                     || 'Asi paso desapercibido 52 dias (21/06->12/08) la ultima vez. Revisar el cron last-catalog-sync-hourly y los logs de la Edge Function last-catalog-sync.',
          'kind', 'last-catalog-sync'
        ),
        timeout_milliseconds := 10000
      );
      insert into public.last_catalog_alert_log (kind, detail) values ('last-catalog-stale', v_count || ' cuenta(s)');
    end if;
  end if;

  select string_agg(
           format('%s (%s / %s) - agotado desde %s', ecp.product_name, coalesce(ecp.external_brand_name, '?'),
                  coalesce(ecp.external_channel, '?'), ecp.disabled_since::text),
           chr(10) order by ecp.disabled_since
         ), count(*)
    into v_list, v_count
  from public.external_catalog_product ecp
  where ecp.source = 'lastapp' and ecp.is_enabled = false and ecp.missing_since is null
    and ecp.disabled_since is not null and ecp.disabled_since < now() - interval '3 hours';

  if v_count > 0
     and not exists (
       select 1 from public.last_catalog_alert_log
       where kind = 'last-catalog-product-down' and sent_at >= now() - interval '3 hours'
     ) then
    select decrypted_secret into v_secret from vault.decrypted_secrets where name = 'cron_secret';
    if v_secret is not null then
      perform net.http_post(
        url     := 'https://xzmpnchlguibclvxyynt.supabase.co/functions/v1/system-alert',
        headers := jsonb_build_object('Content-Type', 'application/json', 'x-cron-secret', v_secret),
        body    := jsonb_build_object(
          'subject', v_count || ' producto(s) agotados en Last hace mas de 3h',
          'message', left(v_list, 3500),
          'kind', 'last-catalog-sync'
        ),
        timeout_milliseconds := 10000
      );
      insert into public.last_catalog_alert_log (kind, detail) values ('last-catalog-product-down', v_count || ' producto(s)');
    end if;
  end if;

  select string_agg(
           format('%s (%s) org %s local %s - %s productos caidos', y.external_brand_name,
                  coalesce(y.external_channel, '?'), y.external_org_id, y.external_location_id, y.n_down),
           chr(10) order by y.n_down desc
         ), count(*)
    into v_list, v_count
  from (
    select external_brand_name, external_channel, external_org_id, external_location_id,
           count(*) filter (where is_enabled = false) as n_down
    from public.external_catalog_product
    where source = 'lastapp' and missing_since is null and external_brand_name is not null
    group by external_brand_name, external_channel, external_org_id, external_location_id
    having count(*) >= 3 and count(*) filter (where is_enabled = false) = count(*)
  ) y;

  if v_count > 0
     and not exists (
       select 1 from public.last_catalog_alert_log
       where kind = 'last-catalog-brand-down' and sent_at >= now() - interval '3 hours'
     ) then
    select decrypted_secret into v_secret from vault.decrypted_secrets where name = 'cron_secret';
    if v_secret is not null then
      perform net.http_post(
        url     := 'https://xzmpnchlguibclvxyynt.supabase.co/functions/v1/system-alert',
        headers := jsonb_build_object('Content-Type', 'application/json', 'x-cron-secret', v_secret),
        body    := jsonb_build_object(
          'subject', 'URGENTE: ' || v_count || ' marca(s) entera(s) caida(s) en Last',
          'message', 'Todos los productos de estas marcas/canal/local estan apagados a la vez (posible caida de plataforma, no un agotado puntual):' || chr(10) || chr(10) || v_list,
          'kind', 'last-catalog-sync'
        ),
        timeout_milliseconds := 10000
      );
      insert into public.last_catalog_alert_log (kind, detail) values ('last-catalog-brand-down', v_count || ' marca(s)');
    end if;
  end if;

  select string_agg(
           format('%s (%s) - desaparecido %s', ecp.product_name, coalesce(ecp.external_brand_name, '?'), ecp.missing_since::text),
           chr(10) order by ecp.missing_since
         ), count(*)
    into v_list, v_count
  from public.external_catalog_product ecp
  where ecp.source = 'lastapp' and ecp.missing_since is not null
    and ecp.missing_since >= now() - interval '3 hours';

  if v_count > 0
     and not exists (
       select 1 from public.last_catalog_alert_log
       where kind = 'last-catalog-missing' and sent_at >= now() - interval '3 hours'
     ) then
    select decrypted_secret into v_secret from vault.decrypted_secrets where name = 'cron_secret';
    if v_secret is not null then
      perform net.http_post(
        url     := 'https://xzmpnchlguibclvxyynt.supabase.co/functions/v1/system-alert',
        headers := jsonb_build_object('Content-Type', 'application/json', 'x-cron-secret', v_secret),
        body    := jsonb_build_object(
          'subject', v_count || ' referencia(s) desaparecidas del catalogo de Last',
          'message', left(v_list, 3500),
          'kind', 'last-catalog-sync'
        ),
        timeout_milliseconds := 10000
      );
      insert into public.last_catalog_alert_log (kind, detail) values ('last-catalog-missing', v_count || ' referencia(s)');
    end if;
  end if;

exception when others then
  begin
    if not exists (
      select 1 from public.last_catalog_alert_log
      where kind = 'last-catalog-watchdog-error' and sent_at >= now() - interval '30 minutes'
    ) then
      select decrypted_secret into v_secret from vault.decrypted_secrets where name = 'cron_secret';
      if v_secret is not null then
        perform net.http_post(
          url     := 'https://xzmpnchlguibclvxyynt.supabase.co/functions/v1/system-alert',
          headers := jsonb_build_object('Content-Type', 'application/json', 'x-cron-secret', v_secret),
          body    := jsonb_build_object(
            'subject', 'last_catalog_watchdog FALLO',
            'message', 'El vigia del espejo de Last lanzo una excepcion y no pudo completar su chequeo: ' || sqlerrm,
            'kind', 'last-catalog-watchdog-error'
          ),
          timeout_milliseconds := 10000
        );
        insert into public.last_catalog_alert_log (kind, detail) values ('last-catalog-watchdog-error', sqlerrm);
      end if;
    end if;
  exception when others then
    null;
  end;
  raise;
end;
$function$;

comment on function public.last_catalog_watchdog() is
  'Vigia del espejo de disponibilidad de Last (external_catalog_product): espejo rancio (>3h sin sync), producto agotado sostenido (>3h), marca entera caida, referencias recien desaparecidas (<3h). Aviso por EXCEPCION via system-alert, antiruido de 3h por kind (30min para el fallo del propio vigia) en last_catalog_alert_log. Silencioso si no hay nada que reportar.';

revoke all on function public.last_catalog_watchdog() from public, anon, authenticated;

select cron.schedule(
  'last-catalog-watchdog',
  '*/15 12-23 * * *',
  $cron$select public.last_catalog_watchdog()$cron$
);