-- Aplicada: SÍ (Julio, 11/08 ~11:45, por MCP; sin drift — verificada carácter
-- a carácter contra la definición viva ANTES de aplicar). Verificado en vivo:
-- 2 triggers con rastro, 0 catch mudos.
--
-- ENCARGO fix/limpieza-kds-viejo-y-prevencion (11/08 mediodía) · Tarea B —
-- "que no se pueda encolar a una impresora apagada".
--
-- RECON que CORRIGE la causa raíz asumida por el encargo (§1): no se pudo
-- reproducir "se encolaron tickets a una impresora inactiva" porque eso no es
-- lo que pasó. Leídas las 7 funciones que hacen `insert into print_job`
-- (enqueue_print_job, tg_auto_print_on_accept, tg_auto_print_bag_on_ready,
-- reprint_order, reprint_order_by_token, enqueue_test_print[_by_token]): las 5
-- primeras YA filtran `is_active` correctamente al elegir impresora — no hace
-- falta ningún cambio ahí. Las 2 de test print (enqueue_test_print[_by_token])
-- imprimen a un p_printer_id EXPLÍCITO elegido por un admin, sin filtro — es
-- una acción manual dirigida, no un enrutado automático; no se toca (caso de
-- uso distinto, probar una impresora concreta aunque esté "apagada" en BBDD
-- puede ser justo lo que se quiere hacer al diagnosticarla).
--
-- Lo que pasó de verdad en Carabanchel (fechas exactas, printer.updated_at):
-- la impresora "Cocina" estuvo ACTIVA desde su alta (08/08 18:57) hasta las
-- 09/08 12:19:50; los 76 print_job se crearon TODOS entre 08/08 18:57:10 y
-- 09/08 12:18:04 — es decir, TODOS mientras "Cocina" estaba activa, y CERO
-- después de desactivarla (verificado: `count(*) filter (where created_at >=
-- '2026-08-09 12:19:50+00')` = 0 sobre los 76). "Impre" (misma IP) se creó a
-- las 12:19:26, 24 segundos ANTES de desactivar "Cocina" — un swap deliberado
-- de impresora que dejó huérfanos los trabajos ya en cola.
--
-- El fallo mudo real: `delete_printer` SÍ bloquea si hay print_job pendientes
-- ("cancélalos primero"), pero `upsert_printer` (la RPC que también desactiva,
-- vía p_is_active=false) NO tiene ese mismo control — desactivar una impresora
-- con trabajos detrás no avisa ni bloquea. NO se replica aquí el bloqueo de
-- delete_printer en upsert_printer a propósito: con las tablets pidiendo
-- claim_print_jobs cada ~3s, en cualquier momento de servicio normal hay casi
-- siempre algún print_job en 'pending' de los últimos segundos (trabajo vivo,
-- no atascado) — bloquear la desactivación con ese mismo predicado habría
-- hecho casi imposible apagar una impresora que se acaba de estropear en
-- mitad del servicio, cuando lo que hace falta es apagarla YA. La red de
-- seguridad correcta es el Aviso 5 añadido a 20260816T0902_db_health_watchdog.sql
-- (print_job no terminal en impresora is_active=false, cada minuto, sin
-- exigir persistencia) — detecta lo mismo sin arriesgar bloquear una
-- desactivación de emergencia legítima.
--
-- Lo que SÍ es un fallo mudo real y distinto, y es lo que arregla este
-- fichero: cuando un pedido se acepta y el local se ha quedado sin NINGUNA
-- impresora activa (o, para la bolsa al "Listo", sin ninguna activa con
-- doc_type 'bag'), tg_auto_print_on_accept / tg_auto_print_bag_on_ready
-- simplemente no insertan nada — el pedido se acepta y NUNCA imprime, y el
-- `exception when others then null` que envuelve todo el cuerpo se traga
-- CUALQUIER error real también, en silencio absoluto. Se arregla dejando
-- rastro visible en print_route_failure_log (que recoge el Aviso 6 del vigía,
-- 0902) y cambiando el `null` final por `raise warning` (visible en logs de
-- Postgres, sigue sin bloquear la entrada del pedido).
--
-- Validado por MCP (nombres temporales _tmp_check_*, tabla mímica de `sale`,
-- trigger real disparado con INSERT/UPDATE): local fantasma sin impresoras →
-- 1 fila en el rastro (no 2, aunque entren 2 pedidos en la ventana de 30min:
-- el dedup por local+detalle funciona); Carabanchel real (con "Impre" activa)
-- → 0 filas, sin falso positivo. Descartado sin tocar las funciones reales.

do $$
begin
  if not exists (select 1 from pg_proc where pronamespace='public'::regnamespace and proname='tg_auto_print_on_accept') then
    raise exception 'print_job_no_fallar_en_silencio: falta tg_auto_print_on_accept — RECON desactualizado, parar';
  end if;
  if not exists (select 1 from pg_proc where pronamespace='public'::regnamespace and proname='tg_auto_print_bag_on_ready') then
    raise exception 'print_job_no_fallar_en_silencio: falta tg_auto_print_bag_on_ready — RECON desactualizado, parar';
  end if;
end $$;

-- La crea también 20260816T0902 (Tarea C) — `if not exists` en los dos
-- ficheros a propósito, para que el orden de aplicación no importe.
create table if not exists public.print_route_failure_log (
  id           bigint generated by default as identity primary key,
  account_id   uuid not null,
  location_id  uuid not null,
  sale_id      uuid,
  doc_type     text,
  detail       text not null,
  created_at   timestamptz not null default now()
);

comment on table public.print_route_failure_log is
  'RLS deny-all intencional. Rastro de "pedido aceptado sin impresora activa a '
  'la que imprimir" (fix/limpieza-kds-viejo-y-prevencion, 11/08) — lo escriben '
  'los triggers de auto-impresión, lo lee db_health_watchdog(). Sin retención '
  'explícita aquí (tabla de bajo volumen, un local mal configurado no genera '
  'mucho ruido); revisar manualmente si crece.';

alter table public.print_route_failure_log enable row level security;

create index if not exists idx_print_route_failure_log_created_at
  on public.print_route_failure_log (location_id, created_at desc);

CREATE OR REPLACE FUNCTION public.tg_auto_print_on_accept()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare
  v_printer record; v_doc text; v_i int;
  v_fire boolean := false;
  v_bag_on_ready boolean := false;
begin
  if new.order_status = 'accepted' then
    if TG_OP = 'INSERT' then v_fire := true;
    elsif old.order_status is distinct from new.order_status then v_fire := true;
    end if;
  end if;

  if v_fire then
    begin
      select coalesce(k.bag_on_ready, false) into v_bag_on_ready
      from kitchen_time_config k where k.location_id = new.location_id;
      v_bag_on_ready := coalesce(v_bag_on_ready, false);

      if not exists (
        select 1 from printer
        where account_id = new.account_id and location_id = new.location_id and is_active
      ) then
        -- Fallo mudo evitado (11/08): sin esto, el pedido se acepta y JAMÁS
        -- imprime nada, sin que nadie se entere. Dedup: 1 rastro por local
        -- cada 30min, no uno por pedido (evita spam si el local lleva horas
        -- sin ninguna impresora activa).
        insert into print_route_failure_log (account_id, location_id, sale_id, doc_type, detail)
        select new.account_id, new.location_id, new.id, null,
               'tg_auto_print_on_accept: sin impresoras activas en el local'
        where not exists (
          select 1 from print_route_failure_log
          where location_id = new.location_id
            and detail = 'tg_auto_print_on_accept: sin impresoras activas en el local'
            and created_at >= now() - interval '30 minutes'
        );
      end if;

      for v_printer in
        select id, doc_types, copies from printer
        where account_id = new.account_id and location_id = new.location_id and is_active
      loop
        foreach v_doc in array v_printer.doc_types loop
          -- La BOLSA se salta aquí SOLO si este local imprime bolsa al "Listo".
          if not (v_doc = 'bag' and v_bag_on_ready)
             and not exists (
               select 1 from print_job pj
               where pj.sale_id = new.id and pj.source = 'auto'
                 and pj.doc_type = v_doc and pj.printer_id = v_printer.id
             ) then
            for v_i in 1..greatest(1, coalesce(v_printer.copies, 1)) loop
              insert into print_job (account_id, location_id, printer_id, sale_id, doc_type, payload, source, status)
              values (new.account_id, new.location_id, v_printer.id, new.id, v_doc,
                      jsonb_build_object('sale_id', new.id, 'mode', 'by_order'), 'auto', 'pending');
            end loop;
          end if;
        end loop;
      end loop;
    exception when others then
      -- Antes: `null` — se tragaba CUALQUIER error en silencio absoluto.
      -- Ahora: visible en logs de Postgres, sigue sin bloquear la entrada
      -- del pedido (regla de la casa: nunca bloquear por esto).
      raise warning 'tg_auto_print_on_accept: fallo inesperado para sale %: %', new.id, sqlerrm;
    end;
  end if;

  return new;
end;
$function$;

CREATE OR REPLACE FUNCTION public.tg_auto_print_bag_on_ready()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
declare v_printer record; v_i int; v_on boolean := false;
begin
  if new.order_status = 'awaiting_collection'
     and old.order_status is distinct from new.order_status then
    begin
      select coalesce(k.bag_on_ready, false) into v_on
      from kitchen_time_config k where k.location_id = new.location_id;
      if not coalesce(v_on, false) then return new; end if;

      if not exists (
        select 1 from printer
        where account_id = new.account_id and location_id = new.location_id
          and is_active and 'bag' = any(doc_types)
      ) then
        insert into print_route_failure_log (account_id, location_id, sale_id, doc_type, detail)
        select new.account_id, new.location_id, new.id, 'bag',
               'tg_auto_print_bag_on_ready: bag_on_ready activo pero sin impresora activa con doc_type bag'
        where not exists (
          select 1 from print_route_failure_log
          where location_id = new.location_id
            and detail = 'tg_auto_print_bag_on_ready: bag_on_ready activo pero sin impresora activa con doc_type bag'
            and created_at >= now() - interval '30 minutes'
        );
      end if;

      for v_printer in
        select id, copies from printer
        where account_id = new.account_id and location_id = new.location_id
          and is_active and 'bag' = any(doc_types)
      loop
        if not exists (
          select 1 from print_job pj
          where pj.sale_id = new.id and pj.source = 'auto'
            and pj.doc_type = 'bag' and pj.printer_id = v_printer.id
        ) then
          for v_i in 1..greatest(1, coalesce(v_printer.copies, 1)) loop
            insert into print_job (account_id, location_id, printer_id, sale_id, doc_type, payload, source, status)
            values (new.account_id, new.location_id, v_printer.id, new.id, 'bag',
                    jsonb_build_object('sale_id', new.id, 'mode', 'by_order'), 'auto', 'pending');
          end loop;
        end if;
      end loop;
    exception when others then
      raise warning 'tg_auto_print_bag_on_ready: fallo inesperado para sale %: %', new.id, sqlerrm;
    end;
  end if;
  return new;
end;
$function$;

notify pgrst, 'reload schema';
