-- ENCARGO (11/08 tarde) — cola con reintento para system-alert.
--
-- BUG DE FONDO QUE CIERRA: net.http_post es fire-and-forget. Los watchdogs
-- escribian la fila de antiruido en db_health_alert_log INMEDIATAMENTE despues
-- de perform net.http_post(...), sin saber si la llamada iba a tener exito. Si
-- sufria un timeout de DNS (3 observados el 11/08 15:00), el sistema daba el
-- aviso por enviado y consumia la ventana de silencio (15min/24h/60min) aunque
-- el correo nunca hubiera salido.
--
-- DISENO: reutiliza el patron de customer_notification/training_notice (cola +
-- status + attempts + cron que drena, hasta 3 intentos). Los 3 emisores SQL ya
-- no llaman a net.http_post: encolan. El drenaje resuelve contra
-- net._http_response por request_id.
--
-- (b) El antiruido se escribe SOLO al confirmar un 200 — nunca al encolar.
-- (a) Meta-aviso por dos vias independientes: raise warning (no depende de
--     Resend/DNS) + aviso por el canal normal con antiruido propio de 60min
--     por CREACION (si exigiera confirmacion, un canal caido nunca lo
--     consumiria y encolaria una fila por minuto durante toda la caida).
--
-- CONCURRENCIA: los dos bucles del drenaje llevan `for update skip locked`,
-- mismo patron que claim_print_jobs, para que dos ejecuciones solapadas no
-- disparen el mismo aviso dos veces.
--
-- CORRECCION APLICADA AL APLICAR (Claude, 11/08): los manejadores `exception
-- when others` de los 3 emisores encolaban un aviso y despues hacian `raise`.
-- Al relanzar, la transaccion se revierte y ESA FILA ENCOLADA SE PIERDE — el
-- aviso de "el vigia ha fallado" nunca habria salido. Se anade `raise warning`
-- ANTES del encolado en los tres: el warning va a los logs del servidor y no
-- se revierte. El encolado se mantiene (si la condicion persiste, el siguiente
-- tick lo vuelve a intentar).

do $$
begin
  if not exists (select 1 from pg_proc where pronamespace='public'::regnamespace and proname='db_health_watchdog') then
    raise exception 'system_alert_queue_reintento: falta db_health_watchdog — parar';
  end if;
  if not exists (select 1 from pg_proc where pronamespace='public'::regnamespace and proname='db_health_writer_regression_check') then
    raise exception 'system_alert_queue_reintento: falta db_health_writer_regression_check — parar';
  end if;
  if not exists (select 1 from pg_proc where pronamespace='public'::regnamespace and proname='db_health_stale_devices_report') then
    raise exception 'system_alert_queue_reintento: falta db_health_stale_devices_report — parar';
  end if;
  if not exists (select 1 from information_schema.columns where table_schema='net' and table_name='_http_response' and column_name='status_code') then
    raise exception 'system_alert_queue_reintento: net._http_response sin status_code — parar';
  end if;
end $$;

-- 1) Tabla cola
create table if not exists public.system_alert_queue (
  id              bigint generated by default as identity primary key,
  kind            text not null,
  debounce_kind   text,
  subject         text not null,
  message         text not null,
  status          text not null default 'pending' check (status in ('pending', 'sent', 'failed')),
  attempts        int not null default 0,
  request_id      bigint,
  last_error      text,
  created_at      timestamptz not null default now(),
  last_attempt_at timestamptz,
  sent_at         timestamptz
);
comment on table public.system_alert_queue is
  'Cola con reintento para el canal system-alert (11/08) — patron de '
  'customer_notification/training_notice. RLS deny-all. Retencion 7 dias para '
  'filas resueltas.';
alter table public.system_alert_queue enable row level security;
create index if not exists idx_system_alert_queue_drain
  on public.system_alert_queue (status, request_id) where status = 'pending';
create index if not exists idx_system_alert_queue_created_at
  on public.system_alert_queue (created_at);
revoke all on table public.system_alert_queue from public, anon, authenticated;

-- 2) Helper: encolar con antiduplicado
CREATE OR REPLACE FUNCTION public._queue_system_alert(p_kind text, p_subject text, p_message text, p_debounce_kind text DEFAULT NULL)
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
begin
  if p_debounce_kind is not null and exists (
    select 1 from public.system_alert_queue
    where debounce_kind = p_debounce_kind and status = 'pending'
  ) then
    return;
  end if;
  insert into public.system_alert_queue (kind, subject, message, debounce_kind)
  values (p_kind, p_subject, p_message, p_debounce_kind);
end;
$function$;
revoke all on function public._queue_system_alert(text, text, text, text) from public, anon, authenticated;

-- 3) Drenaje
CREATE OR REPLACE FUNCTION public.system_alert_queue_drain()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
declare
  v_row         record;
  v_status_code int;
  v_error_msg   text;
  v_secret      text;
  v_new_request bigint;
  v_to_fire     int;
  v_degraded_n  int;
begin
  -- 3.1) Resolver peticiones en vuelo. FOR UPDATE SKIP LOCKED: si dos
  -- ejecuciones se solapan, la segunda salta las filas en curso.
  for v_row in
    select * from public.system_alert_queue
    where status = 'pending' and request_id is not null
    order by id
    for update skip locked
  loop
    select status_code, error_msg into v_status_code, v_error_msg
    from net._http_response where id = v_row.request_id;

    if found then
      if v_status_code = 200 then
        update public.system_alert_queue
          set status = 'sent', sent_at = now(), request_id = null
          where id = v_row.id;
        -- El antiruido se consume AQUI, con la entrega confirmada.
        if v_row.debounce_kind is not null then
          insert into public.db_health_alert_log (kind, detail)
            values (v_row.debounce_kind, 'entregado por la cola, intento ' || v_row.attempts);
        end if;
      else
        update public.system_alert_queue set
          status     = case when v_row.attempts >= 3 then 'failed' else 'pending' end,
          request_id = null,
          last_error = coalesce('http ' || v_status_code, v_error_msg, 'fallo desconocido')
        where id = v_row.id;
      end if;
    elsif v_row.last_attempt_at < now() - interval '2 minutes' then
      -- pg_net no ha respondido tras 2min. Mismo case: si era el 3er intento,
      -- 'failed' — sin esto se quedaria en limbo permanente.
      update public.system_alert_queue set
        status     = case when v_row.attempts >= 3 then 'failed' else 'pending' end,
        request_id = null,
        last_error = 'sin respuesta de pg_net tras 2min'
      where id = v_row.id;
    end if;
  end loop;

  -- 3.2) Disparar
  select decrypted_secret into v_secret from vault.decrypted_secrets where name = 'cron_secret';
  select count(*) into v_to_fire
  from public.system_alert_queue
  where status = 'pending' and request_id is null and attempts < 3;

  if v_secret is null then
    if v_to_fire > 0 then
      raise warning 'system_alert_queue_drain: secret cron_secret ausente en Vault, % aviso(s) sin poder dispararse', v_to_fire;
    end if;
  else
    for v_row in
      select * from public.system_alert_queue
      where status = 'pending' and request_id is null and attempts < 3
      order by id
      for update skip locked
    loop
      select net.http_post(
        url     := 'https://xzmpnchlguibclvxyynt.supabase.co/functions/v1/system-alert',
        headers := jsonb_build_object('Content-Type', 'application/json', 'x-cron-secret', v_secret),
        body    := jsonb_build_object('subject', v_row.subject, 'message', v_row.message, 'kind', v_row.kind),
        timeout_milliseconds := 10000
      ) into v_new_request;
      update public.system_alert_queue
        set request_id = v_new_request, attempts = attempts + 1, last_attempt_at = now()
        where id = v_row.id;
    end loop;
  end if;

  delete from public.system_alert_queue
    where status in ('sent', 'failed') and created_at < now() - interval '7 days';

  -- 3.3) Meta-aviso. "Degradado" = al menos un FALLO CONFIRMADO en la ultima
  -- hora (last_error solo se rellena al confirmar un fallo, nunca al disparar).
  select count(*) into v_degraded_n
  from public.system_alert_queue
  where last_error is not null and created_at >= now() - interval '60 minutes';

  if v_degraded_n > 0 then
    raise warning 'system_alert_queue_drain: % aviso(s) sin poder entregarse en la ultima hora — el canal de alertas puede estar caido', v_degraded_n;
    if not exists (
      select 1 from public.system_alert_queue
      where debounce_kind = 'db-health-alert-queue-degraded' and created_at >= now() - interval '60 minutes'
    ) then
      perform public._queue_system_alert(
        'db-health',
        'Canal de alertas degradado — ' || v_degraded_n || ' aviso(s) sin entregar en 1h',
        v_degraded_n || ' aviso(s) llevan en cola sin poder entregarse en la ultima hora (fallo de red/DNS o Resend). '
          || 'Revisa system_alert_queue y los logs de Postgres.',
        'db-health-alert-queue-degraded'
      );
    end if;
  end if;
exception when others then
  raise warning 'system_alert_queue_drain: excepcion no controlada: %', sqlerrm;
  raise;
end;
$function$;
comment on function public.system_alert_queue_drain() is
  'Drena system_alert_queue cada minuto (cron system-alert-queue-drain): '
  'resuelve peticiones en vuelo contra net._http_response (200->sent, otro '
  'resultado->reintenta o failed a la 3a) y dispara las listas. El antiruido '
  'se escribe SOLO al confirmar un 200 — nunca al encolar. Meta-aviso por dos '
  'vias si hay fallos confirmados en la ultima hora.';
revoke all on function public.system_alert_queue_drain() from public, anon, authenticated;

-- 4) db_health_watchdog: encola en vez de llamar a net.http_post
CREATE OR REPLACE FUNCTION public.db_health_watchdog()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
declare
  v_snap            jsonb;
  v_waiting         int;
  v_total_conn      int;
  v_max_conn        int;
  v_n_snapshots     int;
  v_n_breaching     int;
  v_stuck_print     int;
  v_inactive_print  int;
  v_route_failures  int;
begin
  begin
    v_snap       := public.db_health_snapshot();
    v_waiting    := (v_snap->>'waiting_locks')::int;
    v_total_conn := (v_snap->>'total_connections')::int;
    v_max_conn   := (v_snap->>'max_connections')::int;

    insert into public.db_health_snapshot_log
      (total_connections, waiting_locks, oldest_tx_seconds)
    values
      (v_total_conn, v_waiting, (v_snap->>'oldest_tx_seconds')::numeric);

    delete from public.db_health_snapshot_log where checked_at < now() - interval '48 hours';
    delete from public.db_health_alert_log where sent_at < now() - interval '30 days';

    -- Aviso 1 — bloqueos sostenidos
    select count(*), count(*) filter (where waiting_locks > 3)
      into v_n_snapshots, v_n_breaching
      from public.db_health_snapshot_log
      where checked_at >= now() - interval '2 minutes';
    if v_n_snapshots >= 2 and v_n_breaching = v_n_snapshots
       and not exists (
         select 1 from public.db_health_alert_log
         where kind = 'db-health-lock' and sent_at >= now() - interval '15 minutes'
       ) then
      perform public._queue_system_alert(
        'db-health',
        'BBDD con bloqueos — ' || v_waiting || ' proceso(s) esperando lock, sostenido >2min',
        'db_health_watchdog detecto mas de 3 procesos esperando lock en ' || v_n_snapshots
          || ' snapshots consecutivos de los ultimos 2 minutos (ahora mismo: ' || v_waiting || ').' || chr(10)
          || 'Conexiones de cliente: ' || v_total_conn
          || '. Transaccion mas antigua: ' || (v_snap->>'oldest_tx_seconds') || 's.' || chr(10)
          || 'Asi empezo el incidente del 11/08. Revisar pg_stat_activity ya.',
        'db-health-lock'
      );
    end if;

    -- Aviso 2 — conexiones de CLIENTE cerca del maximo
    if v_max_conn > 0 and v_total_conn > 0.8 * v_max_conn
       and not exists (
         select 1 from public.db_health_alert_log
         where kind = 'db-health-connections' and sent_at >= now() - interval '15 minutes'
       ) then
      perform public._queue_system_alert(
        'db-health',
        'BBDD cerca del limite de conexiones — ' || v_total_conn || '/' || v_max_conn,
        'db_health_watchdog detecto ' || v_total_conn || ' conexiones de CLIENTE activas de un maximo de '
          || v_max_conn || ' (>80%).' || chr(10)
          || 'Revisar pg_stat_activity: puede ser el mismo patron del 11/08.',
        'db-health-connections'
      );
    end if;

    -- Aviso 4 — print_job en pending >2h
    select count(*) into v_stuck_print
    from print_job
    where status = 'pending' and created_at < now() - interval '2 hours';
    if v_stuck_print > 0
       and not exists (
         select 1 from public.db_health_alert_log
         where kind = 'db-health-print-stuck' and sent_at >= now() - interval '60 minutes'
       ) then
      perform public._queue_system_alert(
        'db-health',
        v_stuck_print || ' trabajo(s) de impresion atascados >2h',
        'db_health_watchdog detecto ' || v_stuck_print || ' print_job en pending desde hace mas de 2 horas.' || chr(10)
          || 'Asi se acumularon los 76 de Carabanchel (08-09/08) durante 3 dias sin que nadie se enterara.',
        'db-health-print-stuck'
      );
    end if;

    -- Aviso 5 — print_job no terminal en impresora inactiva
    select count(*) into v_inactive_print
    from print_job pj
    join printer p on p.id = pj.printer_id
    where pj.status in ('pending', 'sent') and p.is_active = false;
    if v_inactive_print > 0
       and not exists (
         select 1 from public.db_health_alert_log
         where kind = 'db-health-print-inactive-printer' and sent_at >= now() - interval '60 minutes'
       ) then
      perform public._queue_system_alert(
        'db-health',
        v_inactive_print || ' trabajo(s) de impresion encolados a impresora INACTIVA',
        'db_health_watchdog detecto ' || v_inactive_print || ' print_job (pending/sent) cuya impresora tiene is_active=false.' || chr(10)
          || 'Nunca se van a imprimir: claim_print_jobs solo reclama de impresoras activas.',
        'db-health-print-inactive-printer'
      );
    end if;

    -- Aviso 6 — pedidos aceptados sin ninguna impresora activa
    select count(*) into v_route_failures
    from public.print_route_failure_log
    where created_at >= now() - interval '10 minutes';
    if v_route_failures > 0
       and not exists (
         select 1 from public.db_health_alert_log
         where kind = 'db-health-print-no-active-printer' and sent_at >= now() - interval '60 minutes'
       ) then
      perform public._queue_system_alert(
        'db-health',
        'Pedido(s) aceptado(s) sin impresora activa en el local',
        'db_health_watchdog detecto ' || v_route_failures || ' aviso(s) en print_route_failure_log de los ultimos 10 minutos.',
        'db-health-print-no-active-printer'
      );
    end if;

  exception when others then
    -- raise warning PRIMERO: va a los logs del servidor y NO se revierte con
    -- el raise de abajo. El encolado si se revierte — se mantiene porque si la
    -- condicion persiste, el siguiente tick lo vuelve a intentar.
    raise warning 'db_health_watchdog: excepcion: %', sqlerrm;
    if not exists (
      select 1 from public.db_health_alert_log
      where kind = 'db-health-watchdog-error' and sent_at >= now() - interval '30 minutes'
    ) then
      perform public._queue_system_alert(
        'db-health-watchdog-error',
        'db_health_watchdog FALLO',
        'El vigia de salud de BBDD lanzo una excepcion: ' || sqlerrm,
        'db-health-watchdog-error'
      );
    end if;
    raise;
  end;
end;
$function$;
comment on function public.db_health_watchdog() is
  'Snapshot cada minuto y ENCOLA en system_alert_queue (ya no net.http_post '
  'directo — 11/08) ante 5 condiciones, cada una con su antiruido en '
  'db_health_alert_log (consumido solo al confirmarse la entrega). Nunca falla '
  'en silencio.';

-- 5) db_health_writer_regression_check
CREATE OR REPLACE FUNCTION public.db_health_writer_regression_check()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
declare
  v_snap    jsonb;
  v_writers int;
begin
  begin
    v_snap := public.db_health_snapshot();
    select count(*) into v_writers
    from pg_proc p
    join pg_namespace n on n.oid = p.pronamespace
    where n.nspname = 'public' and p.prosrc ~* 'update\s+(public\.)?kds_device';

    insert into public.db_health_snapshot_log
      (total_connections, waiting_locks, oldest_tx_seconds, writer_count)
    values (
      (v_snap->>'total_connections')::int,
      (v_snap->>'waiting_locks')::int,
      (v_snap->>'oldest_tx_seconds')::numeric,
      v_writers
    );

    if v_writers <> 3
       and exists (select 1 from public.db_health_snapshot_log where writer_count = 3)
       and not exists (
         select 1 from public.db_health_alert_log
         where kind = 'db-health-writer-regression' and sent_at >= now() - interval '24 hours'
       ) then
      perform public._queue_system_alert(
        'db-health',
        'REGRESION: ' || v_writers || ' funciones escriben kds_device (se esperaban 3)',
        'Alguien ha vuelto a meter una escritura de last_seen_at en una funcion de LECTURA de kds_device '
          || '(el incidente completo del 11/08, de nuevo).' || chr(10)
          || 'Esperado: kds_heartbeat, report_device_app_version, set_device_mode_by_token — y nada mas.',
        'db-health-writer-regression'
      );
    end if;
  exception when others then
    raise warning 'db_health_writer_regression_check: excepcion: %', sqlerrm;
    if not exists (
      select 1 from public.db_health_alert_log
      where kind = 'db-health-writer-regression-check-error' and sent_at >= now() - interval '30 minutes'
    ) then
      perform public._queue_system_alert(
        'db-health-writer-regression-check-error',
        'db_health_writer_regression_check FALLO',
        'El chequeo de regresion de escritores (cada 15 min) lanzo una excepcion: ' || sqlerrm,
        'db-health-writer-regression-check-error'
      );
    end if;
    raise;
  end;
end;
$function$;

-- 6) db_health_stale_devices_report
CREATE OR REPLACE FUNCTION public.db_health_stale_devices_report()
RETURNS void
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path TO 'public'
AS $function$
declare
  v_list  text;
  v_count int;
begin
  select string_agg(
           format('%s (%s) — ultimo latido: %s',
             d.label, coalesce(l.name, 'sin local'), coalesce(d.last_seen_at::text, 'nunca')),
           chr(10) order by d.last_seen_at nulls first
         ), count(*)
    into v_list, v_count
  from kds_device d
  left join locations l on l.id = d.location_id
  where d.is_active
    and (d.last_seen_at is null or d.last_seen_at < now() - interval '30 days');

  if v_count is null or v_count = 0 then
    return;
  end if;

  perform public._queue_system_alert(
    'db-health-stale-devices',
    v_count || ' dispositivo(s) KDS activo(s) sin latido hace mas de 30 dias',
    'Solo REPORTE — ninguna baja automatica. Revisar si siguen en uso o dar de baja a mano (is_active=false):'
      || chr(10) || chr(10) || v_list
  );
exception when others then
  raise warning 'db_health_stale_devices_report: excepcion: %', sqlerrm;
  perform public._queue_system_alert(
    'db-health-stale-devices-error',
    'db_health_stale_devices_report FALLO',
    'El reporte diario de dispositivos fantasma lanzo una excepcion: ' || sqlerrm
  );
  raise;
end;
$function$;

select cron.schedule(
  'system-alert-queue-drain',
  '* * * * *',
  $cron$select public.system_alert_queue_drain()$cron$
);

notify pgrst, 'reload schema';