// tests/unit/modules/kitchen/formatosDeCompra.poblacionReal.ts
//
// POBLACIÓN REAL, no inventada (regla 31). Son los 165 enlaces vivos de
// Foodint (51ad1792-6629-4ef7-833a-b57b09a86710) que tienen denominación de
// proveedor y formato, leídos de la base el 19/09/2026 con esta consulta:
//
//   select ri.name, sup.name, s.supplier_item_name, u.dimension, u.abbreviation,
//          f.name, f.qty_in_base, f.qty_per_parent, p.qty_in_base
//   from article_supplier s
//   join recipe_item ri  on ri.id = s.recipe_item_id
//   join supplier sup    on sup.id = s.supplier_id
//   join kitchen_unit u  on u.id = ri.base_unit_id
//   join recipe_item_purchase_format f on f.id = s.purchase_format_id
//   left join recipe_item_purchase_format p on p.id = f.parent_format_id
//   where s.account_id = '51ad1792-…' and s.is_active and ri.is_active
//     and s.supplier_item_name is not null and btrim(s.supplier_item_name) <> '';
//
// El `account_id` va en la consulta a propósito (regla 9): sin él entraría el
// catálogo plantilla de Folvy Interno y la cifra no sería de nadie.

export interface EnlaceReal {
  articulo: string
  proveedor: string
  texto: string
  baseDim: string
  baseAbbr: string
  formato: string
  qtyInBase: number
  qtyPerParent: number | null
  innerQtyInBase: number | null
}

type Fila = [string, string, string, string, string, string, number, number | null, number | null]

const FILAS: Fila[] = [
["Aceite Alto Oleico","CLOUDTOWN, S.L.","ACEITE GIRASOL 25 LT","volume","ml","Bidón",25000,null,null],
["Aceite Alto Oleico","MAKRO DISTRIBUCION MAYORISTA SA","METRO Chef Aceite girasol alto oléico 25 litros","volume","ml","Bidón",25000,null,null],
["Aceite de Birria","CLOUDTOWN, S.L.","ACEITE BIRRIA CAJA 3 UD DE 1 KG","weight","g","Caja",3000,3,1000],
["Aceite de Oliva Suave 0,4º","MAKRO DISTRIBUCION MAYORISTA SA","RIOBA aceite oliva virgen extra botella 250ml","volume","ml","Botella",1000,null,null],
["Agua Mineral 50 CL","BODEGA DE VALLECAS S.L","AGUA MINERAL FUENTEVERA 50CL","unit","ud","Ud",1,1,1],
["Agua Mineral 50 CL","BODEGA DE VALLECAS S.L","Agua Mineral 50 CL","unit","ud","Ud",1,1,1],
["Agua Mineral 50 CL","MAKRO DISTRIBUCION MAYORISTA SA","FONT VELLA Agua mineral natural en botella de 0,5 L contiene 24 unidades","unit","ud","Pack",24,null,null],
["Albahaca","MAKRO DISTRIBUCION MAYORISTA SA","METRO Chef Albahaca bandeja 125g","weight","g","Paquete",125,null,null],
["Alubias rojas","CLOUDTOWN, S.L.","ALUBIA ROJA COCIDA EXTRA CAJA 6 UD DE 3 KG","weight","g","Caja",18000,6,3000],
["Alubias rojas","MAKRO DISTRIBUCION MAYORISTA SA","alubia cocida roja lata 1600gne (2500 g)","weight","g","Lata",1600,null,null],
["Arroz Largo","CLOUDTOWN, S.L.","ARROZ LARGO NOMEN PAQUETE 1 KG","weight","g","Unidad",1000,null,null],
["Arroz Largo","CLOUDTOWN, S.L.","ARROZ LARGO NOMEN PAQUETE 1 KG","weight","g","Unidad",1000,null,null],
["Arroz Largo","MAKRO DISTRIBUCION MAYORISTA SA","METRO Chef Arroz largo en bolsa 5 Kg","weight","g","Paquete",5000,null,null],
["Bacon Ahumado","CLOUDTOWN, S.L.","BACON CRISPY 1/2 LONCHAS 70% CAJA 4,8 KG CONG.","weight","g","Caja 4,8 kg",4800,null,null],
["Bacon Ahumado","MAKRO DISTRIBUCION MAYORISTA SA","aro bacon loncheado 500 g contiene 2 unidades (total 1 kg)","weight","g","Paquete",1000,null,null],
["Berenjena negra","MAKRO DISTRIBUCION MAYORISTA SA","METRO Chef Berenjena negra en malla 2 Kg","weight","g","Malla",2000,null,null],
["Bobina papel cocina","MAKRO DISTRIBUCION MAYORISTA SA","aro bobina 1 capa 300 metros 3 rollos","unit","ud","Paquete",1,1,1],
["Bobina Secamanos 2 Capas 3 X 90","MAKRO DISTRIBUCION MAYORISTA SA","aro Bobina ARO 2 capas 100 metros 3 rollos","unit","ud","Paquete",3,1,3],
["Bolsa Ay Mamita","CLOUDTOWN, S.L.","SOBRE AMERICANO AY MAMITA CAJA 250 UD","unit","ud","Caja",250,null,null],
["Bolsa Big Mike","CLOUDTOWN, S.L.","SOBRE AMERICANO BIG MIKE'S CAJA 250 UD","unit","ud","Caja",250,null,null],
["Bolsa Birria Burrito","CLOUDTOWN, S.L.","SOBRE AMERICANO BIRRIA BURRITO CAJA 250 D","unit","ud","Caja",250,null,null],
["Bolsas de papel kraft grandes sin asas","MANUFACTURAS CATOR, S.L.","P - Bolsa SOS Big Mikes a 2 tintas 24x14x40 - 2 T + 100% Fondo (250 Unidades) - CLOUDTOWN","unit","ud","Paquete",250,null,null],
["Bolsas Dos Coyotes","CLOUDTOWN, S.L.","SOBRE AMERICANO DOS COYOTES CAJA 250 UD","unit","ud","caja",250,null,null],
["Bolsas Personalizadas Ay Mamita","CLOUDTOWN, S.L.","SOBRE AMERICANO AY MAMITA CAJA 250 UD","unit","ud","caja",250,null,null],
["Bolsas Personalizadas Big Mikes","CLOUDTOWN, S.L.","SOBRE AMERICANO BIG MIKE'S CAJA 250 UD","unit","ud","Caja",250,null,null],
["Bolsas Personalizadas Birria Burrito","CLOUDTOWN, S.L.","SOBRE AMERICANO BIRRIA BURRITO CAJA 250 D","unit","ud","Caja",250,null,null],
["Bolsas Personalizadas Korean","CLOUDTOWN, S.L.","SOBRE AMERICANO KDB CAJA 250 UD","unit","ud","Caja",250,null,null],
["Bolsas Personalizadas Korean","CLOUDTOWN, S.L.","SOBRE AMERICANO KDB CAJA 250 UD","unit","ud","Caja",250,null,null],
["Bolsas Sos sin Asas Kraft 22x14x37 Cm","CLOUDTOWN, S.L.","Bolsa SOS 80gr reciclada 24x14x40 color kraft 250 UNIDADES","unit","ud","Caja 250 ud",250,null,null],
["Bowl","CLOUDTOWN, S.L.","TAZON BLANCP BUCKATY 700 ML 24 OZ 360 Unidad 360 UNIDADES","unit","ud","Paquete",360,null,null],
["Bowl","CLOUDTOWN, S.L.","TAPA RPET 360 UNIDADES","unit","ud","Paquete",360,null,null],
["Caja Dos Coyotes","CLOUDTOWN, S.L.","ESTUCHE FA 190X120X75 \"COYOTE\" CAJA 250 UD","unit","ud","Caja",250,null,null],
["CAJA GENERICA 1350Ml","CLOUDTOWN, S.L.","ESTUCHE FA TAKE AWAY GRANDE CAJA 450 UD","unit","ud","Caja",450,450,1],
["CAJA GENERICA 780 Ml","CLOUDTOWN, S.L.","ESTUCHE FA 190X120X75 ANONIMO CAJA 250 UD","unit","ud","caja",250,null,null],
["Caja Hamburguesa Chivuos","CLOUDTOWN, S.L.","ESTUCHE CONICO BURGER 120X120 CHIVUOS CAJA 450 UD","unit","ud","Caja",450,null,null],
["Caja Milanesa Haus","CLOUDTOWN, S.L.","ESTUCHE MICRO KPK \"MILANESA HAUS\" CAJA 100 UD","unit","ud","Paquete",100,null,null],
["Cajas pinsa blanca","CLOUDTOWN, S.L.","CAJAS PINSA BLANCA 360x240x45 (100 un/pq)","unit","ud","PPaquete",100,null,null],
["CAJAS PINSA BLANCA 360x240x45 (100 un/pq)","CLOUDTOWN, S.L.","CAJAS PINSA BLANCA 360x240x45 (100 un/pq)","unit","ud","Paquete",100,null,null],
["Caldo de Birria","CLOUDTOWN, S.L.","CALDO BIRRIA CAJA 3 UD DE 2 KG CONG","weight","g","Caja",6000,3,2000],
["Caldo Vegetal en Polvo","MAKRO DISTRIBUCION MAYORISTA SA","Knorr Professional caldo vegetal en polvo 1kg","weight","g","Bote",1000,null,null],
["Caracola Espinaca y Queso Feta 230 grs","OLIMPO GOURMET, S.L","Caracol Esp./Queso 235gr Stamos (UMCC)","unit","ud","Caja",30,null,null],
["Carne de Birria","CLOUDTOWN, S.L.","CARNE BIRRIA CAJA 3 UD DE 2 KG CONG","weight","g","Caja",6000,3,2000],
["Cebolla Caramelizada","MAKRO DISTRIBUCION MAYORISTA SA","METRO Chef cebolla caramelizada frasco 900gn","weight","g","Bote",900,null,null],
["Cebolla Morada","CLOUDTOWN, S.L.","CEBOLLA ROJA","weight","g","bolsa",1000,null,null],
["Cebolla Morada","MAKRO DISTRIBUCION MAYORISTA SA","METRO Chef Cebolla morada especial decoracion calibre 60/80 saco 5Kg","weight","g","Bolsa",5000,null,null],
["Cebollino","CLOUDTOWN, S.L.","CEBOLLA TIERNA FINA MANOJO","weight","g","Manojo",125,null,null],
["Cebollino","MAKRO DISTRIBUCION MAYORISTA SA","METRO Chef Cebollino bandeja 125g","weight","g","Manojo",125,null,null],
["Cheesecake de Nutella","CLOUDTOWN, S.L.","TARRICO CHEESECAKE NUTELLA CAJA 15 UD DE 212 ML","unit","ud","Caja",15,null,null],
["Cilantro","CLOUDTOWN, S.L.","CILANTRO MANOJO","weight","g","Paquete",125,null,null],
["Cilantro","MAKRO DISTRIBUCION MAYORISTA SA","METRO Chef Cilantro bolsa 125g","weight","g","Paquete",125,null,null],
["Coca-Cola Original Lata","BODEGA DE VALLECAS S.L","COCA COLA LATA 33CL.","unit","ud","Pack",24,null,null],
["Coca-Cola Original Lata","BODEGA DE VALLECAS S.L","Coca-Cola Original Lata","unit","ud","Pack",24,null,null],
["Coca-Cola Original Lata","MAKRO DISTRIBUCION MAYORISTA SA","Coca-Cola sabor original en lata 33 cl en pack contiene 24 latas","unit","ud","Pack",24,null,null],
["Coca-Cola Zero Lata","BODEGA DE VALLECAS S.L","Coca-Cola Zero Lata","unit","ud","paquete",24,null,null],
["Coca-Cola Zero Lata","MAKRO DISTRIBUCION MAYORISTA SA","Coca-Cola zero azúcar en lata 33 cl contiene 24 latas","unit","ud","Pack",24,null,null],
["Crema Agria","CLOUDTOWN, S.L.","CREMA FRESCA 30% MG PASTORET UD 2 KG","weight","g","Unidad 2 kg",2000,null,null],
["Crema Agria","MAKRO DISTRIBUCION MAYORISTA SA","Pastoret nata crema freiche cocinar 30% materia grasa tarrina 500 g","weight","g","Bote",500,null,null],
["Crispy Wings","COHELDI, S.L.","POLLO ALITAS CRUJIENTES CRISPY WINGS","weight","g","Caja",2200,null,null],
["DELICIAS DE POLLO SOUTHERN","COHELDI, S.L.","POLLO DELICIAS SUREÑAS METEORITOS 35G","weight","g","Caja",2200,null,null],
["Envoltorio Pergamino 31x31 blanco","MANUFACTURAS CATOR, S.L.","Papel Antigrasa Blanco 31x31","unit","ud","Paquete",1000,null,null],
["Falafel","OLIMPO GOURMET, S.L","Falafel Preparado 1kg Take","weight","g","Bolsa",1000,null,null],
["Fanta Limón Lata","BODEGA DE VALLECAS S.L","FANTA LIMON 33CL LATA","unit","ud","Caja",24,null,null],
["Fanta Limón Lata","BODEGA DE VALLECAS S.L","Fanta Limón Lata","unit","ud","Caja",24,null,null],
["Fanta Limón Lata","MAKRO DISTRIBUCION MAYORISTA SA","Fanta limón lata 33cl contiene 24 latas","unit","ud","Paquete",24,null,null],
["Fanta Naranja Lata","BODEGA DE VALLECAS S.L","FANTA NARANJA 33CL LATA","unit","ud","Pack",24,null,null],
["Fanta Naranja Lata","BODEGA DE VALLECAS S.L","Fanta Naranja Lata","unit","ud","Pack",24,null,null],
["Fanta Naranja Lata","MAKRO DISTRIBUCION MAYORISTA SA","Fanta de naranja lata 33cl contiene 24 unidades","unit","ud","Pack",24,null,null],
["Film transparente","MAKRO DISTRIBUCION MAYORISTA SA","METRO PROFESSIONAL film transparente 7 micras 300mx29cm","unit","ud","Unidad",1,null,null],
["Focaccia XXL","CLOUDTOWN, S.L.","FOCACCIA XXL 9 UD / CAJA","unit","ud","Caja",9,null,null],
["Guacamole","CLOUDTOWN, S.L.","GUACAMOLE CONGELADO CAJA 8 BOLSAS DE 500 GR","weight","g","caja",4000,null,null],
["Guacamole","MAKRO DISTRIBUCION MAYORISTA SA","METRO Chef guacamole suave tarrina 1 Kg","weight","g","Bote",1000,null,null],
["Hamburguesa Mixta 85 Grs 142 Und","CLOUDTOWN, S.L.","PREPARADO CARNE MIXTA 85 GR CAJA 142 UD CONG.","unit","ud","Caja",142,null,null],
["Huevos","MAKRO DISTRIBUCION MAYORISTA SA","METRO Chef huevo suelo tamaño M-L huevera 2,5 docenas","unit","ud","Carton",30,null,null],
["Humus","MAKRO DISTRIBUCION MAYORISTA SA","METRO Chef hummus tarrina 900g","weight","g","Bote",900,null,null],
["Jamon Dulce","MAKRO DISTRIBUCION MAYORISTA SA","METRO Chef jamón cocido loncheado 150 g contiene 3 unidades (total 450 g)","weight","g","Pack 3x150 g",450,null,null],
["Kebab Pollo Loncheado","AMIRSA HOSTELERIA, S.L.","Pollo loncheado 10x1Kg","weight","g","Caja",10000,10,1000],
["Kebab Pollo Loncheado","COHELDI, S.L.","KEBAB DE POLLO GOURMET 1KG","weight","g","Caja",10000,10,1000],
["Kebab Ternera Loncheado","AMIRSA HOSTELERIA, S.L.","Ternera loncheada 10x1Kg","weight","g","Caja",10000,10,1000],
["Kebab Ternera Loncheado","COHELDI, S.L.","KEBAB DE VACUNO GOURMET 1 KG","weight","g","Caja",8000,8,1000],
["Lechuga Romana","CLOUDTOWN, S.L.","ENSALADA LARGA ROMANA BOLSA DE 2 UD","weight","g","Bolsa",650,null,null],
["Lechuga Romana","MAKRO DISTRIBUCION MAYORISTA SA","Lechuga romana en bandeja 2u","weight","g","Bolsa",400,null,null],
["Lima","MAKRO DISTRIBUCION MAYORISTA SA","Limas ma 2 kg","weight","g","Bolsa",2000,null,null],
["MAHOU 5 ESTRELLAS","MAKRO DISTRIBUCION MAYORISTA SA","Mahou cerveza Cinco Estrellas 33cl contiene 28 latas","unit","ud","Pack",28,null,null],
["MARQUESA CHOCO - AVELLANA","CLOUDTOWN, S.L.","QUE MARQUESA CHOCO AVELLANA CJ 24 U 150 GR CONG","unit","ud","caja",24,null,null],
["MARQUESA DULCE DE LECHE","CLOUDTOWN, S.L.","QUE MARQUESA DULDE LECHE CJ 24 U 160 GR CONG","unit","ud","caja",24,null,null],
["Mayonesa Hellmann´s","MAKRO DISTRIBUCION MAYORISTA SA","METRO Chef Mayonesa en cubo 5 L","weight","g","Bote",5000,null,null],
["Mayonesa Trufa","CLOUDTOWN, S.L.","MAYONESA TRUFA CAJA 9 DOYPACK DE 1 KG","weight","g","Caja",9000,9,1000],
["Milanesa de Pollo Rebozado","NOBLEZA VACUNA SL","Milanesa de pollo","unit","ud","Paquete",6,1,6],
["Milanesa Ternera Rebozado","CLOUDTOWN, S.L.","MILANESA TERNERA CJ 4 KG CONG","unit","ud","caja",16,1,0.25],
["Pan Bocadillos","CLOUDTOWN, S.L.","Bollo Cocido 100g (26u)","unit","ud","Caja",26,null,null],
["Pan Bocadillos","EUROPASTRY, S.A.","Bollo Cocido 100g (26u)","unit","ud","Caja",26,null,null],
["Pan de Pita 21 cm","OLIMPO GOURMET, S.L","Pita 21cm 80uds Select (UMCC)","unit","ud","Caja",80,8,10],
["Pan Hamburguesa","CLOUDTOWN, S.L.","PAN BURGER FRESH 85652 CJ 60 UD DE 65 GR CONG","unit","ud","Caja",60,null,null],
["Pan Hamburguesa","CLOUDTOWN, S.L.","Burger Beach (80u)","unit","ud","Caja",80,null,null],
["Pan Hamburguesa","EUROPASTRY, S.A.","Burger Beach (80u)","unit","ud","Caja",80,null,null],
["Papel Aluminio 40 cmX250 Mts","MAKRO DISTRIBUCION MAYORISTA SA","METRO PROFESSIONAL papel aluminio 200 metros x 44 centimetros 12 micras","unit","ud","rollo",1,null,null],
["Papel Aluminio Punteado 30 X 27","CLOUDTOWN, S.L.","Papel aluminio punteado 30cm x 27cm 12my CAJA 500 HOJAS","unit","ud","Paquete",500,null,null],
["Papel de horno","MAKRO DISTRIBUCION MAYORISTA SA","aro Papel horno 50m","length","m","Rollo",50,null,null],
["PAPEL SILICONADO DE HORNO KRAFT (CAJA 500 UND)","CLOUDTOWN, S.L.","Papel Siliconado de Horno Kraft (EMBALAJE: 500 UNIDADES)","unit","ud","Caja",500,null,null],
["Pasta Trufada","CLOUDTOWN, S.L.","CREMA TARTUFATA CARVI LATA 350 GR","weight","g","Bote",350,null,null],
["Patatas Bastón","CLOUDTOWN, S.L.","PATATA FRITA CASERA HOME-STYLE CAJA 12,5 KG CONG","weight","g","Caja 5 bolsas  12,5 kg",12500,null,null],
["Patatas Bastón","COHELDI, S.L.","PATATA RUSTICA 10-10 CON PIEL","weight","g","Caja",10000,4,2500],
["Peperoni Loncheado","CLOUDTOWN, S.L.","PEPPERONI CENTRAL PIZZA Bolsa 1 Kg .(Caja 6 Kg)","weight","g","Estuche",1000,null,null],
["Peperoni Loncheado","CLOUDTOWN, S.L.","PEPPERONI CENTRAL PIZZA Bolsa 1 Kg .(Caja 6 Kg)","weight","g","Paquete",1000,null,null],
["Peperoni Loncheado","MAKRO DISTRIBUCION MAYORISTA SA","METRO Chef peperoni en lonchas 1kg","weight","g","Estuche",1000,null,null],
["Pepinillos Agridulce en Rodajas","CLOUDTOWN, S.L.","PEPINILLO AGRIDULCE RODAJA CUBO 2,2 KG","weight","g","Bote",2200,null,null],
["Pepinillos Agridulce en Rodajas","MAKRO DISTRIBUCION MAYORISTA SA","METRO Chef pepinillo agridulce en rodajas 1900gne","weight","g","Bote",1900,null,null],
["Pesto Verde","CLOUDTOWN, S.L.","PESTO GENOVESE BROVER BOTE 900 GR","weight","g","Bote",900,null,null],
["Pesto Verde","MAKRO DISTRIBUCION MAYORISTA SA","METRO Chef Salsa pesto genovese en bote 980g","weight","g","Bote",980,null,null],
["Piedra Limpia Plancha","MAKRO DISTRIBUCION MAYORISTA SA","METRO PROFESSIONAL Piedra limpiadora ideal planchas 6 uds","unit","ud","Paquete 6 ud",6,null,null],
["Pollo Mechado","CLOUDTOWN, S.L.","POLLO MECHADO CAJA 3 UD DE 2 KG CONG","weight","g","Caja",6000,3,2000],
["Portes","CLOUDTOWN, S.L.","PORTES","unit","ud","Unidad",1,null,null],
["Pulled Pork","CLOUDTOWN, S.L.","PULLED PORK CAJA 3 UD DE 2 KG CONG","weight","g","Caja",6000,null,null],
["Queso Cheddar Loncheado","CLOUDTOWN, S.L.","QUESO BURGER LONCHAS ORIGINAL 1,4 KG","weight","g","Paquete",1400,null,null],
["Queso Cheddar Loncheado","MAKRO DISTRIBUCION MAYORISTA SA","METRO Chef queso cheddar rojo loncheado 1kg","weight","g","Paquete",1000,null,null],
["Queso Cheddar Loncheado","PRODUCTOS LÁCTEOS TGT, S.A.","CHEDDAR COLOR LONCHAS ESC.1KG","weight","g","Paquete",1000,null,null],
["Queso Gouda Loncheado","CLOUDTOWN, S.L.","QUESO GOUDA LONCHAS 500 GR CAJA 12 UD","weight","g","Caja",6000,12,500],
["Queso Gouda Loncheado","MAKRO DISTRIBUCION MAYORISTA SA","Lafuente queso gouda bandeja 1 kg contiene 50 lonchas","weight","g","Paquete",1000,null,null],
["Queso Gouda Loncheado","PRODUCTOS LÁCTEOS TGT, S.A.","QUESO GOUDA LONCH.BOCAT.FS 1K","weight","g","Paquete",1000,null,null],
["Queso Mozarela","CLOUDTOWN, S.L.","MOZZARELLA RALLADA CONGELADA BOLSA 2 KG","weight","g","Paquete",2000,1,2000],
["Queso Mozarela","MAKRO DISTRIBUCION MAYORISTA SA","METRO Chef mozzarella rallada bolsa 1 Kg","weight","g","Bolsa",1000,null,null],
["Queso Mozarela","PRODUCTOS LÁCTEOS TGT, S.A.","BELLA BIANCA MOZ.RALL.(4)1,5KG.","weight","g","Bolsa",1500,null,null],
["Queso Parmesano","MAKRO DISTRIBUCION MAYORISTA SA","METRO Chef queso grana padano D.O.P. cuña 16 meses 1 Kg aproximado","weight","g","Pieza",1000,null,null],
["Queso Rulo de Cabra","CLOUDTOWN, S.L.","QUESO RULO MADURADO MEZCLA GUZMAN UD 850 GR","weight","g","Pieza 850 g",850,null,null],
["Queso Rulo de Cabra","CLOUDTOWN, S.L.","QUESO RULO MADURADO MEZCLA GUZMAN UD 850 GR","weight","g","Pieza 850 g",850,null,null],
["Rollitos de Queso Feta","OLIMPO GOURMET, S.L","Rollitos Queso 5Kg. Ioniki (UMCC)","weight","g","Caja",5000,null,null],
["Rollo Papel Térmico 80x76","MAKRO DISTRIBUCION MAYORISTA SA","SIGMA rollo registradora papel térmico 80x76m 10 unidades","unit","ud","Caja",10,null,null],
["Salsa BBQ","CLOUDTOWN, S.L.","SALSA BARBACOA CAJA 3 UD DE 1 KG","weight","g","Caja",3000,3,1000],
["Salsa Coreana","CLOUDTOWN, S.L.","SALSA COREANA CAJA 3 UD DE 1 KG","weight","g","Caja",3000,3,1000],
["Salsa Coreana","CLOUDTOWN, S.L.","SALSA COREANA CAJA 3 UD DE 1 KG CONG","weight","g","Caja",3000,3,1000],
["Salsa Mayo Chipotle","CLOUDTOWN, S.L.","SALSA MAYONESA CHIPOTLE CAJA 3 UD DE 1 KG","weight","g","Caja",3000,3,1000],
["Salsa Melt","CLOUDTOWN, S.L.","SALSA MELT CAJA 3 UD DE 1 KG","weight","g","Caja",3000,3,1000],
["Salsa Mil Islas","CLOUDTOWN, S.L.","SALSA MIL ISLAS CAJA 3 UD DE 1 KG","weight","g","Caja",3000,3,1000],
["Salsa Sweet Chilli","CLOUDTOWN, S.L.","SALSA CHIPOTLE SWEET CHILI CAJA 3 UD DE 1 KG","volume","ml","Caja",3000,3,1000],
["Salsa Tzatziki 200g","OLIMPO GOURMET, S.L","+S.Tzatziki 200grs Paltsidis","unit","ud","Caja",12,null,null],
["Salsa Verde","CLOUDTOWN, S.L.","SALSA VERDE MEXICANA COSTEÑA 220 GR","weight","g","Bote 220 g",220,null,null],
["Salsa White Bbq","CLOUDTOWN, S.L.","SALSA WHITE BBQ CAJA 3 UD DE 1 KG","weight","g","Caja",3000,3,1000],
["SALSA Yogur","COHELDI, S.L.","SALSA KEBAB (YOGOURT) 1L","weight","g","Botella",1000,null,null],
["SALSA Yogur","MAKRO DISTRIBUCION MAYORISTA SA","Chovi salsa de yogur 820 ml","weight","g","Botella",820,null,null],
["Salsero 120 Cc","CLOUDTOWN, S.L.","TARRINA 100 cc TR/BL PP INYECCION (PAQUETE 100 UD)","unit","ud","Paquete",100,null,null],
["Salsero 120 Cc","MANUFACTURAS CATOR, S.L.","Tarrina microondable negra 120 ml PP","unit","ud","Pack",630,null,null],
["Salsero 60 cc","MANUFACTURAS CATOR, S.L.","Tarrina microondable 60 ml PP","unit","ud","Pack",375,null,null],
["Salsero con Tapa de 60cc","CLOUDTOWN, S.L.","SALSERA PP+ TAPA BISABRA 2 OZ 60ml (50 UD)","unit","ud","Paquete",50,null,null],
["Salsero Pp 120 Cc con Tapa","CLOUDTOWN, S.L.","TAPA PP PARA TARRINAS DE 70-100-125 C.C. (EMBALAJE: PQ 100 U.)","unit","ud","Paquete",100,null,null],
["Servilletas 30 x 40","CLOUDTOWN, S.L.","Servilleta master servis","unit","ud","Caja",4500,null,null],
["Servilletas 30 x 40","MAKRO DISTRIBUCION MAYORISTA SA","METRO PROFESSIONAL Servilleta natural 30x40cm 150 unidades","unit","ud","Paquete",150,null,null],
["Solomillo de Pollo Prefrito Piri-piri","CLOUDTOWN, S.L.","SOLOMILLO POLLO PREFRITO PIRI-PIRI CJ 5X1 KG CONG","weight","g","Caja",5000,null,null],
["Solomillo de Pollo Prefrito Piri-piri","CLOUDTOWN, S.L.","SOLOMILLO POLLO PREFRITO PIRI-PIRI CJ 5X1 KG CONG","weight","g","Caja",5000,null,null],
["Soporte Caldo Caja Dos Coyotes","CLOUDTOWN, S.L.","PIEZA INTERIOR SOPORTE CALDO \"COYOTE\" CAJA 250 UD","unit","ud","Caja",250,null,null],
["Sweet Potato Fries","CLOUDTOWN, S.L.","BONIATO BASTON CAJA 5 BOLSAS DE 2 KG CONG","weight","g","Caja",10000,4,2500],
["Sweet Potato Fries","COHELDI, S.L.","BONIATO 11X11 PREFRITO MCCAIN","weight","g","Caja",10000,4,2500],
["Tapa Bowl","CLOUDTOWN, S.L.","TAZON BLANCP BUCKATY 700 ML 24 OZ 360 Unidad 360 UNIDADES","unit","ud","Paquete",360,null,null],
["Tapa Bowl","CLOUDTOWN, S.L.","TAPA RPET 360 UNIDADES","unit","ud","Paquete",360,null,null],
["Tapa Salsero 120 Cc","MANUFACTURAS CATOR, S.L.","Tapa para tarrina microondalbe 100 / 120 / 165 ml PP","unit","ud","Caja 630",630,null,null],
["Tapa Salsero 60 cc","MANUFACTURAS CATOR, S.L.","Tapa para tarrina microondalbe 60 ML y 75 ml Ø 62 MM","unit","ud","Pack",375,null,null],
["Tapa Salsero Grande 120cc","CLOUDTOWN, S.L.","TAPA PP PARA TARRINAS DE 70-100-125 C.C. (EMBALAJE: PQ 100 U.)","unit","ud","Paquete",100,null,null],
["Tarta 3 Leches","CLOUDTOWN, S.L.","TARRICO TRES LECHES CAJA 15 UD DE 212 ML","unit","ud","Caja",15,null,null],
["Tequeños Rellenos de Queso","CLOUDTOWN, S.L.","TEQUEÑOS CLOUDTOWN RELLENOS QUESO CJ 170 UD CONG","unit","ud","Caja",170,2,85],
["Tomate Frito","CLOUDTOWN, S.L.","SALSA PARA PIZZA MUTTI LATA 4,1 KG","weight","g","Lata 4,1 kg",4100,null,null],
["Tomate Frito","MAKRO DISTRIBUCION MAYORISTA SA","Hida tomate frito lata 2500g","weight","g","Lata",2500,null,null],
["Tomate Pera","CLOUDTOWN, S.L.","TOMATE BOC EXTRA","weight","g","paquete",1000,null,null],
["Tomate Pera","MAKRO DISTRIBUCION MAYORISTA SA","METRO Chef Tomate pera calibre M caja 6Kg","weight","g","Caja",6000,null,null],
["Tortilla Maíz 12 cm","CLOUDTOWN, S.L.","TORTILLA MAIZ AMARILLA 12 CM CAJA 12 PAQ DE 20 UD","unit","ud","Caja",240,12,20],
["Tortilla Maíz 12 cm","MAKRO DISTRIBUCION MAYORISTA SA","Mexifoods tortilla maíz 12 cm contiene 18 unidades (300 g aprox.)","unit","ud","Paquete",18,null,null],
["Tortilla Trigo 30 cm","CLOUDTOWN, S.L.","TORTILLA TRIGO 30 CM CAJA 6 PAQ DE 18 UD","unit","ud","Caja",108,6,18],
]

export const ENLACES_REALES: EnlaceReal[] = FILAS.map(
  ([articulo, proveedor, texto, baseDim, baseAbbr, formato, qtyInBase, qtyPerParent, innerQtyInBase]) => ({
    articulo,
    proveedor,
    texto,
    baseDim,
    baseAbbr,
    formato,
    qtyInBase,
    qtyPerParent,
    innerQtyInBase,
  }),
)
